# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
fail_fast: true
exclude: ^.vscode/$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: debug-statements
      - id: check-case-conflict
  - repo: https://github.com/doublify/pre-commit-rust
    rev: "v1.0"
    hooks:
      - id: clippy
        args:
          [
            "--manifest-path",
            "Cargo.toml",
            "--",
            "-D",
            "warnings",
            "-D",
            "clippy::pedantic",
            "-D",
            "clippy::nursery",
            "-D",
            "clippy::all",
          ]
